# Practise Numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.4'

In [3]:
li = [12.23, 13.32, 100, 36.32]
arr =  np.array(li)
print(arr)
 

[ 12.23  13.32 100.    36.32]


In [4]:
# NumPy program to create a 3x3 matrix with values ranging from 2 to 10
x = np.arange(2, 11).reshape(3,3)
x

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [5]:
#NumPy program to create a null vector of size 10 and update sixth value to 11
x = np.zeros((10), dtype='int32')
x[6] = 11
x

array([ 0,  0,  0,  0,  0,  0, 11,  0,  0,  0])

In [6]:
# NumPy program to create an array with values ranging from 12 to 38.
x = np.arange(12, 38)
x

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

In [7]:
#NumPy program to reverse an array
print(x[::-1])

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [8]:
#NumPy program to convert an array to a float type.
x = np.array([1,2,3], dtype='float64')
x

array([1., 2., 3.])

In [9]:
# NumPy program to create a 2d array with 1 on the border and 0 inside.
x = np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
#x[1:4, 1:4]
x[1:-1, 1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
#NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern
x = np.zeros((8, 8))
x[1::2, ::2] = 1
x[::2, 1::2] = 1
x

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [12]:
# NumPy program to convert a list and tuple into arrays
my_list = [1, 2, 3, 4]
x = np.array(my_list)
my_tuple = ([2, 4, 6], [8, 7, 9])
y = np.asarray(my_tuple)
print(x)
print(y)

[1 2 3 4]
[[2 4 6]
 [8 7 9]]


In [13]:
#NumPy program to append values to the end of an array.
x = [10, 20, 30]
arr = np.append(x, [[40, 50, 60], [70, 80, 90]])
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [14]:
#NumPy program to create an empty and a full array.
emp = np.empty((3,4))
emp

array([[9.96730960e-312, 2.81617418e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.18831764e-312, 6.82116729e-043, 7.42379598e-091,
        1.43692966e-051],
       [3.55200112e-062, 4.54684048e+174, 6.48224659e+170,
        4.93432906e+257]])

In [15]:
fl = np.full((3,3), 6)
fl

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [16]:
# NumPy program to find the number of elements of an array, 
#length of one array element in bytes and total bytes consumed by the elements.
x = np.array([1,2,3], dtype='float64')
x


array([1., 2., 3.])

In [17]:
x.size

3

In [18]:
x.itemsize

8

In [19]:
x.nbytes

24

In [20]:
#NumPy program to test whether each element of a 1-D array is also present in a second array.
arr1 = np.array([0, 10, 20, 40, 60])
arr2 = np.array([0, 40])
res = np.in1d(arr1, arr2)
res

array([ True, False, False,  True, False])

In [21]:
#NumPy program to find common values between two arrays.
arr1 = np.array([0, 10, 20, 40, 60])
arr2 = np.array([10, 30, 40])
res = np.intersect1d(arr1, arr2)
res

array([10, 40])

In [22]:
#NumPy program to construct an array by repeating. 
x = np.array([1,2,3,4])
np.tile(x, 2)

array([1, 2, 3, 4, 1, 2, 3, 4])

In [23]:
x = np.array([1,2,3,4])
np.repeat(x,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [24]:
#NumPy program to find the indices of the maximum and minimum values
x = np.array([1,2,3,4,5,6])
print(np.argmax(x))
print(np.argmin(x))

5
0


# Practise Linear Algebra

In [25]:
#NumPy program to compute the multiplication of two given matrixes
x = np.array([[1,0],[1, 4]])
y= np.array([[2, 4], [1,2]])
np.dot(x,y)

array([[ 2,  4],
       [ 6, 12]])

In [26]:
# NumPy program to compute the outer product of two given vectors.
np.outer(x,y)

array([[ 2,  4,  1,  2],
       [ 0,  0,  0,  0],
       [ 2,  4,  1,  2],
       [ 8, 16,  4,  8]])

In [27]:
#cross product of given two vectors
np.cross(x, y)

array([ 4, -2])

In [28]:
#NumPy program to compute the determinant of a given square array. 
x = np.array([[1,2,3],[4,5,6],[7,5,2]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 5, 2]])

In [29]:
np.linalg.det(x)

2.9999999999999964

In [30]:
#Create a 4X2 integer array and Prints its attributes
x= np.array([[1,2], [3,4], [4,5],[6,7]], dtype='int16')
x

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]], dtype=int16)

In [31]:
x.shape

(4, 2)

In [32]:
x.size

8

In [33]:
x.ndim

2

In [34]:
x.itemsize

2

In [35]:
#Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10
x = np.arange(100, 200, 10).reshape(5,2)
x

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [36]:
#Return array of items by taking the third column from all rows
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
sampleArray

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [37]:
sampleArray[:, -1]

array([33, 66, 99])

In [38]:
#Return array of odd rows and even columns from below numpy array
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
sampleArray

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])

In [39]:
sampleArray[::2, 1::2]

array([[ 6, 12],
       [30, 36],
       [54, 60]])

In [40]:
#Create a result array by adding the following two NumPy arrays. Next, modify the result array by 
#calculating the square of each element

arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
res = arrayOne + arrayTwo
res

array([[20, 39, 33],
       [25, 25, 28]])

In [41]:
np.nditer(res)

In [42]:
li = []
for num in np.nditer(res):
    num = num*num
    li.append(num)
print(li)

[400, 1521, 1089, 625, 625, 784]


In [43]:
#Split the array into four equal-sized sub-arrays
x =  np.arange(10,34).reshape(8, 3)
x

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [44]:
res = np.split(x, 4)
res

[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

In [45]:
#Sort following NumPy array
#Case 1: Sort array by the second row
#Case 2: Sort the array by the second column

sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [46]:
np.sort(sampleArray[1])

array([12, 22, 82])

In [47]:
np.sort(sampleArray[:, 2])

array([12, 66, 73])

In [48]:
#sort by row
sampleArray[:, sampleArray[1,:].argsort()]

array([[73, 43, 34],
       [12, 22, 82],
       [66, 94, 53]])

In [49]:
#sort by column
sampleArray[:, sampleArray[:,1].argsort()]

array([[43, 34, 73],
       [22, 82, 12],
       [94, 53, 66]])

In [50]:
#Print max from axis 0 and min from axis 1 from the following 2-D array.
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [51]:
np.max(sampleArray, axis=0)

array([82, 94, 73])

In [52]:
np.min(sampleArray, axis=1)

array([34, 12, 53])

In [53]:
#Delete the second column from a given array and insert the following new column in its place.
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = np.array([[10,10,10]])
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [54]:
sampleArray[:, 1] = newColumn

In [55]:
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])