In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [6]:
x.ndim

1

In [3]:
np.__version__


'1.23.4'

In [4]:
type(x)

numpy.ndarray

In [5]:
#use a tuple to create numpy array
x = np.array((1,2,3,5))
x

array([1, 2, 3, 5])

In [7]:
#2D array
x = np.array([[1, 5, 7, 8,], [8, 9, 5, 6]])
x

array([[1, 5, 7, 8],
       [8, 9, 5, 6]])

In [8]:
x.ndim

2

In [9]:
#3D array
x = np.array([[[1, 5, 7, 8,], [8, 9, 5, 6]], [[5, 6, 8,4], [5, 8, 3, 7]]])
x

array([[[1, 5, 7, 8],
        [8, 9, 5, 6]],

       [[5, 6, 8, 4],
        [5, 8, 3, 7]]])

In [10]:
x.ndim

3

In [11]:
#numpy array indexing
a = np.array([1, 2, 3, 5])
a[0]

1

In [12]:
a[0]+a[3]

6

In [14]:
#2D array
a = np.array([[1,8,5,6],[5,6,9,1]])
a[0, 3]
a[1, 2]

9

In [15]:
#3D array
a = np.array([[[4, 2, 5, 3], [5, 6, 2, 7]], [[8, 2, 0, 3], [6,9,4, 2]]])
a

array([[[4, 2, 5, 3],
        [5, 6, 2, 7]],

       [[8, 2, 0, 3],
        [6, 9, 4, 2]]])

In [16]:
a[0, 1, 2]

2

In [17]:
a[1, 0, 3]

3

In [19]:
#negative indexing
a[1, 1, -1]

2

In [20]:
#array slicing
a = np.array([1, 2, 3, 4, 5, 6])
a[2:]


array([3, 4, 5, 6])

In [21]:
a[0:4:2]

array([1, 3])

In [22]:
a[-4:-1]

array([3, 4, 5])

In [23]:
a[::-1]

array([6, 5, 4, 3, 2, 1])

In [24]:
#2d ARRAY
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
a[1, 0:]

array([5, 6, 7, 8])

In [29]:
a[0, 1::2]

array([2, 4])

In [31]:
a[0:2, 1]

array([2, 6])

In [32]:
a[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [35]:
#copy
arr = np.array([1, 2, 3, 4])
x = arr.copy()
# x[1]=25
print(x)
arr[0] = 42
print(arr)


[1 2 3 4]
[42  2  3  4]


In [46]:
a = np.array([5, 2, 5])
b = np.array([7, 8, 5])
a.copy()
b = a
b[0] = 10
b

array([10,  2,  5])

In [48]:
a = np.array([5, 2, 5])
b = a.view()
a[2] = 15
a
b

array([ 5,  2, 15])

In [50]:
#shape of an array
arr = np.array([[2, 4, 5, 6], [8, 4, 5, 7]])
arr.ndim
arr.shape

(2, 4)

In [52]:
arr = np.array([1, 2, 3, 4])
arr.shape

(4,)

In [53]:
#reshape
#1D-2D
arr = np.array([1, 2, 3, 4, 5, 8, 7, 8, 9, 10, 11, 12])
arr.reshape(4, 3)

array([[ 1,  2,  3],
       [ 4,  5,  8],
       [ 7,  8,  9],
       [10, 11, 12]])