# Numpy(Numerical python) Basics

In [2]:
import numpy as np

In [11]:
#one dimensional array
a = np.array([1, 2, 3], dtype='int16')
print(a)

[1 2 3]


In [4]:
#two dimensional array
b = np.array([[2.0, 3.0, 4.0], [1.0, 5.0, 6.0]])
print(b)

[[2. 3. 4.]
 [1. 5. 6.]]


In [5]:
#get dimension
a.ndim

1

In [6]:
b.ndim

2

In [7]:
#get shape
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [12]:
#get dtypes
a.dtype

dtype('int16')

In [13]:
#get size
a.itemsize

2

In [14]:
a = np.array([1, 2, 3], dtype='int32')
print(a)
a.dtype

[1 2 3]


dtype('int32')

In [15]:
a.itemsize

4

In [17]:
#get total size
a.size * a.itemsize

12

In [18]:
a.nbytes

12

In [19]:
b.dtype

dtype('float64')

In [20]:
b.itemsize

8

In [21]:
b.size

6

In [22]:
b.nbytes

48

# Accessing/changing specific elements rows, columns

In [23]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [24]:
a.shape

(2, 7)

In [42]:
a.size

14

In [25]:
a.ndim

2

In [26]:
#get a specific element [row, column]
a[1, 5]

13

In [27]:
a[0, 0]

1

In [28]:
#getting a sepicific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [29]:
#getting a specific column
a[:, 3]

array([ 4, 11])

In [32]:
#getting a little more fancy[startindex:stopindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [35]:
#changing values
a[1, 5] = 20
print(a)
a[:, 2] = [1, 2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


# 3D array


In [36]:
b = np.array([[[1,2], [3,4]], [[5,6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [38]:
b.ndim

3

In [39]:
b.size

8

In [40]:
b.itemsize

4

In [41]:
b.shape

(2, 2, 2)

In [43]:
b.nbytes

32

In [44]:
#get specific element (work outside in)
b[0, 1, 1]

4

In [45]:
b[:, 1, :]

array([[3, 4],
       [7, 8]])

In [46]:
b[:, 0, :]

array([[1, 2],
       [5, 6]])

In [47]:
b[:, 0, 0]

array([1, 5])

In [53]:
b[:, 0, 0] = [9, 9]
print(b)

[[[9 2]
  [9 9]]

 [[9 6]
  [8 8]]]


In [52]:
#replace 
b[:, 1, :] = [[9, 9], [8, 8]]
print(b)

[[[9 2]
  [9 9]]

 [[9 6]
  [8 8]]]


# initializing different types of arrays

In [55]:
#all 0s matrix
np.zeros((2, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [59]:
#all 1s matrix
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [61]:
#any other number
np.full((2,2), 99, dtype='float')

array([[99., 99.],
       [99., 99.]])

In [62]:
#any other number(full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [63]:
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [67]:
#random decimal numbers
np.random.rand(4, 2, 2)

array([[[0.93943276, 0.99974258],
        [0.59878438, 0.98055389]],

       [[0.41073539, 0.22151512],
        [0.79868798, 0.14719201]],

       [[0.00411693, 0.91629533],
        [0.15251213, 0.98791873]],

       [[0.16864734, 0.6354504 ],
        [0.65261431, 0.05837868]]])

In [72]:
#random int values
np.random.randint(7, size=(3,3))

array([[0, 4, 1],
       [6, 1, 6],
       [1, 5, 4]])

In [76]:
np.random.randint(-4, 8, size=(3,3))

array([[ 4,  5,  3],
       [ 6, -3,  6],
       [ 5, -3,  6]])

In [78]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [81]:
arr =  np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [87]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4, 1:4]= z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [93]:
#be careful when copying arrays
a = [1, 2, 3]

b = a.copy()
b[0] = 12
a
b

[12, 2, 3]

# Mathematics

In [95]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [96]:
a + 2

array([3, 4, 5, 6])

In [97]:
a - 2

array([-1,  0,  1,  2])

In [98]:
a * 2

array([2, 4, 6, 8])

In [99]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [100]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [101]:
a ** 2

array([ 1,  4,  9, 16])

In [102]:
#take sin value
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [103]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# Linear Algebra

In [111]:
a = np.ones((2, 3)) 
print(a)
b = np.full((3,2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [110]:
#find the determinent
c = np.identity(3)
np.linalg.det(c)

1.0

# Statistics

In [113]:
stats = np.array([[1, 2, 3],[4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
np.min(stats)

1

In [116]:
np.max(stats, axis=1)

array([3, 6])

In [118]:
np.sum(stats, axis=0)

array([5, 7, 9])

# Reorganizing arrays

In [125]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((8, 1))
(after)

[[1 2 3 4]
 [5 6 7 8]]


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [126]:
#vertically staking vectors
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.vstack([v1, v2])

array([[1, 2, 3],
       [4, 5, 6]])