# practise numpy


In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [3]:
arr.ndim

1

In [4]:
x = np.array([[1,2,3,4],[5,6,7,8]], dtype='int16')
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int16)

In [5]:
x.ndim


2

In [6]:
x.shape

(2, 4)

In [7]:
arr.shape

(3,)

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr.dtype

dtype('int32')

In [10]:
x.dtype

dtype('int16')

In [11]:
x.nbytes

16

In [12]:
x.size

8

In [13]:
x.itemsize

2

In [14]:
#getting element
x[0, 3]

4

In [15]:
x[1, :]

array([5, 6, 7, 8], dtype=int16)

In [16]:
b = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [17]:
b.shape

(2, 7)

In [18]:
b[:, 5]

array([ 6, 13])

In [19]:
b[0, 4]

5

In [20]:
b[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [21]:
b[0, 1:-1:2]

array([2, 4, 6])

In [22]:
b[1, 3:5]

array([11, 12])

In [23]:
#changing values
b[1, 2] = 15
print(b)
b[0, -1] = 20
print(b)


[[ 1  2  3  4  5  6  7]
 [ 8  9 15 11 12 13 14]]
[[ 1  2  3  4  5  6 20]
 [ 8  9 15 11 12 13 14]]


In [24]:
b[:, 5] = [50, 100]
print(b)

[[  1   2   3   4   5  50  20]
 [  8   9  15  11  12 100  14]]


In [25]:
b[0, 2:4] = [25, 26]
print(b)

[[  1   2  25  26   5  50  20]
 [  8   9  15  11  12 100  14]]


In [26]:
#sicing 2D array
y = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
y[0:3, 2]

array([3, 8])

In [27]:
#3D array

In [28]:
a = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])
print(a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [29]:
a.shape


(2, 2, 3)

In [30]:
a.ndim

3

In [31]:
a.nbytes

48

In [32]:
a.dtype

dtype('int32')

In [33]:
a.itemsize

4

In [34]:
a.size

12

In [35]:
a[0,1,2]

6

In [36]:
a[:, 0, :]

array([[1, 2, 3],
       [7, 8, 9]])

In [37]:
a[:, 1, :]

array([[ 4,  5,  6],
       [10, 11, 12]])

# array creation

In [38]:
np.zeros((3,3), dtype='int16')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [39]:
np.ones((2,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1]])

In [40]:
np.full((2,2), 4)

array([[4, 4],
       [4, 4]])

In [41]:
np.full_like(a, 1)

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [42]:
#random decimal numbers
np.random.rand(2,2,2)

array([[[0.3168136 , 0.70384309],
        [0.73735602, 0.53737348]],

       [[0.82400786, 0.58462001],
        [0.96731877, 0.25117835]]])

In [43]:
#random integers
np.random.randint(5,size=(2,2))

array([[3, 3],
       [3, 4]])

In [44]:
#negative numbers
np.random.randint(-5, 10, size=(3,3))

array([[-1,  6,  1],
       [ 7, -5,  0],
       [-3,  5, -1]])

In [45]:
#identity matrix
np.identity(3, dtype='int16')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

In [46]:
#problem
arr = np.array([[2,4,6]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[2 4 6]
 [2 4 6]
 [2 4 6]]


In [47]:
b = np.array( [ [3,4,6], [0,8,1]])
b


array([[3, 4, 6],
       [0, 8, 1]])

In [48]:
b.size

6

In [49]:
b.itemsize

4

In [50]:
b.nbytes

24

In [51]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
A

array([[ 6,  1,  1],
       [ 4, -2,  5],
       [ 2,  8,  7]])

In [52]:
np.linalg.det(A)

-306.0

In [53]:
A.ndim

2

In [54]:
A.shape

(3, 3)

In [55]:
c=np.identity(4)
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [56]:
np.linalg.det(c)

1.0

In [57]:
d =  np.array([[1,2],[3,4]])
d

array([[1, 2],
       [3, 4]])

In [58]:
np.linalg.det(d)

-2.0000000000000004

In [59]:
e = np.array([[1, 5, 6], [2 , 4, 8], [5, 6, 7]])
e

array([[1, 5, 6],
       [2, 4, 8],
       [5, 6, 7]])

In [60]:
np.linalg.det(e)

62.00000000000001

In [61]:
#copying values
a = np.array([1,5,6])

b = np.copy(a)
b[0] = 10
print (a)
print(b)

[1 5 6]
[10  5  6]


In [62]:
import random
li = [1, 2, 3, 4, 5]
random.choice(li)


3

In [63]:
print(li)

[1, 2, 3, 4, 5]


In [64]:
#arange function
rng = np.arange(10)
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
#linspace(equally linespace)
lspace = np.linspace(1, 20, 10)
lspace


array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [69]:
#empty
emp = np.empty([2, 2])
emp

array([[1., 2.],
       [3., 4.]])

In [70]:
a = np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [71]:
a.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [73]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [77]:
a.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [78]:
#axis in numpy
x = np.array([[1 ,2 ,3], [4, 5, 6], [7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
x.sum(axis = 0) #column

array([12, 15, 18])

In [80]:
x.sum(axis = 1) #row

array([ 6, 15, 24])

In [81]:
#transpose
x.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [82]:
#iteration
x.flat

In [83]:
for i in x.flat:
    print(i)

1
2
3
4
5
6
7
8
9
