In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.4'

In [3]:
#addition of 2 numpy arrays
a = np.array([1 ,2 ,3 ])
b = np.array([4, 5, 6])
c = a+b
c

array([5, 7, 9])

In [4]:
#adding 2D array
a = np.array([[1, 2, 3, 4], [4, 5, 6, 7]])
b = np.array([[7, 8, 9, 10], [5, 6, 8, 9]])
c = a + b
c

array([[ 8, 10, 12, 14],
       [ 9, 11, 14, 16]])

In [5]:
c.ndim

2

In [6]:
c.size

8

In [7]:
c.itemsize

4

In [8]:
c.nbytes

32

In [11]:
c.dtype

dtype('int32')

In [12]:
# Multiplying a matrix (numpy array) by a scalar
a = np.array([[4, 5, 6],[1, 2, 3]])
b = 2*a
b

array([[ 8, 10, 12],
       [ 2,  4,  6]])

In [13]:
# Identity Matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
#Array re-dimensioning
a = np.array([x for x in range(27)])
a.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [24]:
np.arange(1, 20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [25]:
#Array datatype conversion
arr = np.array([[1.2, 2.3, 4.2], [2.5, 3.5, 6.2]])
arr

array([[1.2, 2.3, 4.2],
       [2.5, 3.5, 6.2]])

In [26]:
arr.astype('int')

array([[1, 2, 4],
       [2, 3, 6]])

In [27]:
#btaining Boolean Array from Binary Array
arr = np.array([[1, 0, 0], [0, 1, 1], [1, 0, 1]])
arr

array([[1, 0, 0],
       [0, 1, 1],
       [1, 0, 1]])

In [28]:
arr.astype('bool')

array([[ True, False, False],
       [False,  True,  True],
       [ True, False,  True]])

In [29]:
#Horizontal Stacking of Numpy Arrays
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[2, 4, 6], [5, 7, 9]])
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[2 4 6]
 [5 7 9]]


In [31]:
np.hstack((a,b))

array([[1, 2, 3, 2, 4, 6],
       [4, 5, 6, 5, 7, 9]])

In [32]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6],
       [2, 4, 6],
       [5, 7, 9]])

In [33]:
#Vertically Stacking of Numpy Arrays
a = ([[1,2],[3, 4], [5, 6]])
b = ([[4,5], [6,7], [8,9]])
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [4, 5],
       [6, 7],
       [8, 9]])